# Generated by Django 3.0.7 on 2021-07-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encdec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_key',
            field=models.CharField(default='', max_length=50),
        ),
    ]
