# Generated by Django 3.0.7 on 2021-07-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encdec', '0003_remove_product_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_folder',
            field=models.TextField(default='', max_length=50),
        ),
    ]
