# Generated by Django 3.0.7 on 2021-07-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encdec', '0004_product_product_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.TextField(default='', max_length=50),
        ),
    ]
